name: Publish
on:
  push:
    branches:
      - test4
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: "install dependencies"
        run: npm install
      - name: "Publish"
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: lerna publish --no-private --no-git-tag-version --yes
