name: Publish
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: "Version"
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: npx lerna version --no-private --no-git-tag-version --yes
