name: Publish
on:
  push:
    branches:
      - test4
      - test5
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
           registry-url: 'https://registry.npmjs.org'
      - name: Configure Git User
        run: |
          git config user.name "otterp012"
          git config user.email "otterp012@users.noreply.github.com"
      - name: "publish"
        run: lerna publish --from-package --yes
